### ISSUE TITLE
Plugin-Version 0.6 throws exception (PluginException caused by ClsElementImpl$InvalidMirrorException)

### ISSUE THREAD

**Issue by bric3** [bric3/jd-intellij#23]
Originally reported by: **Christoph Ludwig (Bitbucket: [chludwig_haufe](https://bitbucket.org/chludwig_haufe), GitHub: Unknown)**

----------------------------------------

Hi,

today, IntelliJ 13.1 (build #IU-135.480) prompted me to update the JD-IntelliJ plugin to version 0.6. Since the update, IntelliJ reports an internal error on every startup:

```
C:/Program Files (x86)/Java/jdk1.7.0_21/jre/lib/alt-rt.jar!/java/util/HashMap.class: stub:[]; mirror:[PsiTypeParameter:K, PsiTypeParameter:V] [Plugin: jd-intellij]
com.intellij.diagnostic.PluginException: stub:[]; mirror:[PsiTypeParameter:K, PsiTypeParameter:V] [Plugin: jd-intellij]
	at com.intellij.psi.impl.compiled.ClsFileImpl.a(ClsFileImpl.java:349)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getMirror(ClsFileImpl.java:331)
	at com.intellij.psi.impl.compiled.ClsElementImpl.getMirror(ClsElementImpl.java:154)
	at com.intellij.psi.impl.compiled.ClsElementImpl.getText(ClsElementImpl.java:226)
	at com.intellij.psi.PsiDiamondTypeImpl$2.fun(PsiDiamondTypeImpl.java:228)
	at com.intellij.psi.PsiDiamondTypeImpl$2.fun(PsiDiamondTypeImpl.java:225)
	at com.intellij.openapi.util.text.StringUtil.join(StringUtil.java:1267)
	at com.intellij.openapi.util.text.StringUtil.join(StringUtil.java:1247)
	at com.intellij.openapi.util.text.StringUtil.join(StringUtil.java:1239)
	at com.intellij.psi.PsiDiamondTypeImpl.a(PsiDiamondTypeImpl.java:225)
	at com.intellij.psi.PsiDiamondTypeImpl.access$200(PsiDiamondTypeImpl.java:44)
	at com.intellij.psi.PsiDiamondTypeImpl$1.compute(PsiDiamondTypeImpl.java:145)
	at com.intellij.psi.PsiDiamondTypeImpl$1.compute(PsiDiamondTypeImpl.java:139)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.PsiDiamondTypeImpl.resolveInferredTypesNoCheck(PsiDiamondTypeImpl.java:139)
	at com.intellij.psi.PsiDiamondTypeImpl.resolveInferredTypes(PsiDiamondTypeImpl.java:130)
	at com.intellij.psi.impl.PsiDiamondTypeUtil.a(PsiDiamondTypeUtil.java:63)
	at com.intellij.psi.impl.PsiDiamondTypeUtil.canCollapseToDiamond(PsiDiamondTypeUtil.java:43)
	at com.intellij.codeInspection.ExplicitTypeCanBeDiamondInspection$1.visitNewExpression(ExplicitTypeCanBeDiamondInspection.java:67)
	at com.intellij.psi.impl.source.tree.java.PsiNewExpressionImpl.accept(PsiNewExpressionImpl.java:382)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:74)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:356)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$000(LocalInspectionsPass.java:74)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$3.process(LocalInspectionsPass.java:325)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$3.process(LocalInspectionsPass.java:322)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:119)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:42)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:82)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:91)
	at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:103)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:79)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
Caused by: com.intellij.psi.impl.compiled.ClsElementImpl$InvalidMirrorException: stub:[]; mirror:[PsiTypeParameter:K, PsiTypeParameter:V]
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrors(ClsElementImpl.java:321)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrors(ClsElementImpl.java:312)
	at com.intellij.psi.impl.compiled.ClsTypeParametersListImpl.setMirror(ClsTypeParametersListImpl.java:51)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirror(ClsElementImpl.java:299)
	at com.intellij.psi.impl.compiled.ClsClassImpl.setMirror(ClsClassImpl.java:414)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirror(ClsElementImpl.java:299)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrors(ClsElementImpl.java:324)
	at com.intellij.psi.impl.compiled.ClsClassImpl.setMirror(ClsClassImpl.java:422)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirror(ClsElementImpl.java:299)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrors(ClsElementImpl.java:324)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrors(ClsElementImpl.java:312)
	at com.intellij.psi.impl.compiled.ClsFileImpl.setMirror(ClsFileImpl.java:280)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getMirror(ClsFileImpl.java:328)
	... 39 more

```

The plugin still decompiles class files when I open them in the IDE, but the error makes me worry for the IDE's stability...

Please let me know if you need any additional information.

Regards,
Christoph

----------------------------------------
- Bitbucket: https://bitbucket.org/bric3/jd-intellij/issue/23

**Comment by bric3** [comment]
Let's close this issue, as I don't know if this will be reproduced with recent IntelliJ and newer JD-Core

**Comment by bric3** [comment]
Another one on hotspot 8 (AdoptOpenJdk), with `jdk.internal.dynalink.DefaultBootstrapper`

In the stack trace below, the message indicate the following different between the **stub** (which is how IJ interracts with a class like navigating, autocompletion, etc.), and the mirror which is the decompiled text.

I this case, like in many we see the stub has a **default constructor** (`DefaultBootstrapper`), but the mirror don't have it (jd skips the default constructor if there's no instructions).

```
stub:[PsiMethod:DefaultBootstrapper, PsiMethod:bootstrap, PsiMethod:publicBootstrap, PsiMethod:bootstrapInternal]; mirror:[PsiMethod:bootstrap, PsiMethod:publicBootstrap, PsiMethod:bootstrapInternal]
```

<details><summary><code>ClsFileImpl.decompile</code> (stub) version of <code>jdk.internal.dynalink.DefaultBootstrapper</code></summary>


  // IntelliJ API Decompiler stub source generated from a class file
  // Implementation of methods is not available

package jdk.internal.dynalink;

public class DefaultBootstrapper {
    private static final jdk.internal.dynalink.DynamicLinker dynamicLinker;

    private DefaultBootstrapper() { /* compiled code */ }

    public static java.lang.invoke.CallSite bootstrap(java.lang.invoke.MethodHandles.Lookup caller, java.lang.String name, java.lang.invoke.MethodType type) { /* compiled code */ }

    public static java.lang.invoke.CallSite publicBootstrap(java.lang.invoke.MethodHandles.Lookup caller, java.lang.String name, java.lang.invoke.MethodType type) { /* compiled code */ }

    private static java.lang.invoke.CallSite bootstrapInternal(java.lang.invoke.MethodHandles.Lookup caller, java.lang.String name, java.lang.invoke.MethodType type) { /* compiled code */ }
}

</details>

<details><summary>Java Decompiler (mirror) version of <code>jdk.internal.dynalink.DefaultBootstrapper</code></summary>

/* Location: jar:///Users/brice/.sdkman/candidates/java/8.0.292.hs-adpt/jre/lib/ext/nashorn.jar!/jdk/internal/dynalink/DefaultBootstrapper.class
 * Java language version: 7
 * Class File: 51.0
 * JD-Core Version: 1.1.3
 */

package jdk.internal.dynalink;

import java.lang.invoke.CallSite;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import jdk.internal.dynalink.support.CallSiteDescriptorFactory;































































































public class DefaultBootstrapper
{
    private static final DynamicLinker dynamicLinker = (new DynamicLinkerFactory()).createLinker();














    
    public static CallSite bootstrap(MethodHandles.Lookup caller, String name, MethodType type) {
        return bootstrapInternal(caller, name, type);
    }












    
    public static CallSite publicBootstrap(MethodHandles.Lookup caller, String name, MethodType type) {
        return bootstrapInternal(MethodHandles.publicLookup(), name, type);
    }
    
    private static CallSite bootstrapInternal(MethodHandles.Lookup caller, String name, MethodType type) {
        return dynamicLinker.<CallSite>link(new MonomorphicCallSite(CallSiteDescriptorFactory.create(caller, name, type)));
    }
}


</details>

<details><summary>PluginException / InvalidMirrorException</summary>

```
jar:///Users/brice/.sdkman/candidates/java/8.0.292.hs-adpt/jre/lib/ext/nashorn.jar!/jdk/internal/dynalink/DefaultBootstrapper.class

com.intellij.diagnostic.PluginException: stub:[PsiMethod:DefaultBootstrapper, PsiMethod:bootstrap, PsiMethod:publicBootstrap, PsiMethod:bootstrapInternal]; mirror:[PsiMethod:bootstrap, PsiMethod:publicBootstrap, PsiMethod:bootstrapInternal] [Plugin: jd-intellij]
	at com.intellij.psi.impl.compiled.ClsFileImpl.wrapException(ClsFileImpl.java:387)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getMirror(ClsFileImpl.java:355)
	at com.intellij.psi.impl.compiled.ClsElementImpl.getMirror(ClsElementImpl.java:140)
	at com.intellij.psi.impl.compiled.ClsElementImpl.getTextOffset(ClsElementImpl.java:177)
	at com.intellij.ide.util.EditSourceUtil.getDescriptor(EditSourceUtil.java:41)
	at com.intellij.ide.util.PsiNavigationSupportImpl.getDescriptor(PsiNavigationSupportImpl.java:31)
	at com.intellij.psi.impl.PsiElementBase.navigate(PsiElementBase.java:194)
	at com.intellij.codeInsight.navigation.NavigationUtil.lambda$openFileWithPsiElement$2(NavigationUtil.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.intellij.codeInsight.navigation.NavigationUtil.openFileWithPsiElement(NavigationUtil.java:171)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:235)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:245)
	at com.intellij.util.OpenSourceUtil.navigateToSource(OpenSourceUtil.java:119)
	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:74)
	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:58)
	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:51)
	at com.intellij.util.OpenSourceUtil.openSourcesFrom(OpenSourceUtil.java:19)
	at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.processDoubleClick(EditSourceOnDoubleClickHandler.java:166)
	at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.onDoubleClick(EditSourceOnDoubleClickHandler.java:160)
	at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:30)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:59)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:392)
	at com.intellij.ide.dnd.aware.DnDAwareTree.processMouseEvent(DnDAwareTree.java:45)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: com.intellij.psi.impl.compiled.ClsElementImpl$InvalidMirrorException: stub:[PsiMethod:DefaultBootstrapper, PsiMethod:bootstrap, PsiMethod:publicBootstrap, PsiMethod:bootstrapInternal]; mirror:[PsiMethod:bootstrap, PsiMethod:publicBootstrap, PsiMethod:bootstrapInternal]
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrors(ClsElementImpl.java:274)
	at com.intellij.psi.impl.compiled.ClsClassImpl.setMirror(ClsClassImpl.java:451)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirror(ClsElementImpl.java:256)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrors(ClsElementImpl.java:277)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrors(ClsElementImpl.java:269)
	at com.intellij.psi.impl.compiled.ClsFileImpl.setFileMirror(ClsFileImpl.java:300)
	at com.intellij.psi.impl.compiled.ClsFileImpl.lambda$getMirror$1(ClsFileImpl.java:350)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:218)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getMirror(ClsFileImpl.java:349)
	... 66 more

```

</details>

**Comment by bric3** [comment]
See this thread on the SDK forum : https://intellij-support.jetbrains.com/hc/en-us/community/posts/360010821700-Some-classes-decompiled-via-custom-ClassFileDecompilers-Light-produce-InvalidMirrorException-stub-PsiMethod-Checker-?page=1
