### ISSUE TITLE
Intellij messag: LONG_KEYWORD != JAVA_CODE_REFERENCE [Plugin: jd-intellij]

### ISSUE THREAD

**Issue by bric3** [bric3/jd-intellij#41]
Originally reported by: **Krzysztof Krzemiński (Bitbucket: [kkrzeminski](https://bitbucket.org/kkrzeminski), GitHub: [kkrzeminski](https://github.com/kkrzeminski))**

----------------------------------------

C:/Program Files/Java/jdk1.7.0_67/jre/lib/rt.jar!/sun/nio/ch/ServerSocketChannelImpl.class: LONG_KEYWORD != JAVA_CODE_REFERENCE [Plugin: jd-intellij]
com.intellij.diagnostic.PluginException: LONG_KEYWORD != JAVA_CODE_REFERENCE [Plugin: jd-intellij]
	at com.intellij.psi.impl.compiled.ClsFileImpl.a(ClsFileImpl.java:362)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getMirror(ClsFileImpl.java:344)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getDecompiledPsiFile(ClsFileImpl.java:371)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.a(FoldingUpdate.java:118)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.updateFoldRegions(FoldingUpdate.java:96)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.a(CodeFoldingManagerImpl.java:303)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.buildInitialFoldings(CodeFoldingManagerImpl.java:219)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.initFolding(PsiAwareTextEditorImpl.java:49)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:806)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl3(FileEditorManagerImpl.java:738)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$8.run(FileEditorManagerImpl.java:718)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:117)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:99)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:85)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:715)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:652)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.openFile(FileEditorManagerEx.java:139)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$14.run(FileEditorManagerImpl.java:1046)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:124)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:99)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:85)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openEditor(FileEditorManagerImpl.java:1042)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openTextEditor(FileEditorManagerImpl.java:1107)
	at com.intellij.execution.filters.OpenFileHyperlinkInfo$1.run(OpenFileHyperlinkInfo.java:74)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:900)
	at com.intellij.execution.filters.OpenFileHyperlinkInfo.navigate(OpenFileHyperlinkInfo.java:69)
	at com.intellij.execution.filters.impl.MultipleFilesHyperlinkInfo.navigate(MultipleFilesHyperlinkInfo.java:83)
	at com.intellij.execution.impl.EditorHyperlinkSupport$4.run(EditorHyperlinkSupport.java:123)
	at com.intellij.execution.impl.EditorHyperlinkSupport$2.mouseClicked(EditorHyperlinkSupport.java:85)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.b(EditorImpl.java:5595)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseReleased(EditorImpl.java:5527)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:520)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: com.intellij.psi.impl.compiled.ClsElementImpl$InvalidMirrorException: LONG_KEYWORD != JAVA_CODE_REFERENCE
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrorCheckingType(ClsElementImpl.java:288)
	at com.intellij.psi.impl.compiled.ClsJavaCodeReferenceElementImpl.setMirror(ClsJavaCodeReferenceElementImpl.java:281)
	at com.intellij.psi.impl.compiled.ClsTypeElementImpl.setMirror(ClsTypeElementImpl.java:114)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirror(ClsElementImpl.java:299)
	at com.intellij.psi.impl.compiled.ClsFieldImpl.setMirror(ClsFieldImpl.java:172)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirror(ClsElementImpl.java:299)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrors(ClsElementImpl.java:324)
	at com.intellij.psi.impl.compiled.ClsClassImpl.setMirror(ClsClassImpl.java:420)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirror(ClsElementImpl.java:299)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrors(ClsElementImpl.java:324)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrors(ClsElementImpl.java:312)
	at com.intellij.psi.impl.compiled.ClsFileImpl.setMirror(ClsFileImpl.java:293)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getMirror(ClsFileImpl.java:341)
	... 63 more

----------------------------------------
- Bitbucket: https://bitbucket.org/bric3/jd-intellij/issue/41

**Comment by bric3** [comment]
Cannot reproduce anymore.
