### ISSUE TITLE
Fix  `:runIde` and `:buildSearchableOptions` task

### ISSUE THREAD

**Issue by bric3** [bric3/jd-intellij#58]
When running some gradle tasks, runIde in particular, the `ClassFileDecompiler` class fails to be loaded.

Current stack

```
2021-05-26 10:17:24,693 [   1559]  ERROR - nsions.impl.ExtensionPointImpl - While loading class jd.ide.intellij.JavaLightClassDecompiler: com/intellij/psi/compiled/ClassFileDecompilers$Light [Plugin: jd-intellij] 
com.intellij.diagnostic.PluginException: While loading class jd.ide.intellij.JavaLightClassDecompiler: com/intellij/psi/compiled/ClassFileDecompilers$Light [Plugin: jd-intellij]
        at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:262)
        at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:205)
        at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:113)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getImplementationClass(ExtensionComponentAdapter.java:80)
        at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:39)
        at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:68)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:446)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:401)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:232)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.extensions(ExtensionPointImpl.java:350)
        at com.intellij.openapi.extensions.ExtensionPointName.extensions(ExtensionPointName.java:76)
        at com.intellij.psi.impl.compiled.ClassFileStubBuilder.getAllSubBuilders(ClassFileStubBuilder.java:37)
        at com.intellij.psi.stubs.CompositeBinaryBuilderMap.<init>(CompositeBinaryBuilderMap.java:46)
        at com.intellij.psi.stubs.StubUpdatingIndex$MyIndex.<init>(StubUpdatingIndex.java:307)
        at com.intellij.psi.stubs.StubUpdatingIndex.createIndexImplementation(StubUpdatingIndex.java:292)
        at com.intellij.util.indexing.FileBasedIndexImpl.createIndex(FileBasedIndexImpl.java:445)
        at com.intellij.util.indexing.FileBasedIndexImpl.initIndexStorage(FileBasedIndexImpl.java:388)
        at com.intellij.util.indexing.FileBasedIndexImpl.registerIndexer(FileBasedIndexImpl.java:356)
        at com.intellij.util.indexing.FileBasedIndexDataInitialization.lambda$initAssociatedDataForExtensions$0(FileBasedIndexDataInitialization.java:66)
        at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.executeNestedInitializationTask(IndexInfrastructure.java:177)
        at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.runParallelNestedInitializationTasks(IndexInfrastructure.java:165)
        at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.call(IndexInfrastructure.java:126)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
        at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
        at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
        at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:210)
        at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: com/intellij/psi/compiled/ClassFileDecompilers$Light
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
        at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:380)
        at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:376)
        at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:340)
        at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:259)
        ... 33 more
Caused by: java.lang.ClassNotFoundException: com.intellij.psi.compiled.ClassFileDecompilers$Light PluginClassLoader[jd-intellij, 0.8.0-SNAPSHOT] com.intellij.ide.plugins.cl.PluginClassLoader@59ac8d5e
        at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:115)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 40 more

```

**Comment by bric3** [comment]
The issue happens during `:buildSearchableOptions` task.

**Comment by bric3** [comment]
See https://github.com/JetBrains/gradle-intellij-plugin/issues/673

**Comment by bric3** [comment]
Tried to configure the sandbox, without success

```
prepareSandbox {
    pluginName = intellij.pluginName
    pluginJar = jar.archiveFile.get()
    pluginDependencies = intellij.plugins
}
```

**Comment by bric3** [comment]
OK so this was only a missing depend in `plugin.xml`

https://blog.jetbrains.com/platform/2019/06/java-functionality-extracted-as-a-plugin/
