### ISSUE TITLE
com.intellij.diagnostic.PluginException: stub:{}; mirror:null [Plugin: jd-intellij]

### ISSUE THREAD

**Issue by tursom** [bric3/jd-intellij#66]
jar://C:/Users/tursom/.gradle/wrapper/dists/gradle-6.9-bin/2ecsmyp3bolyybemj56vfn4mt/gradle-6.9/lib/gradle-core-6.9.jar!/org/gradle/api/tasks/bundling/AbstractArchiveTask.class

com.intellij.diagnostic.PluginException: stub:{}; mirror:null [Plugin: jd-intellij]
	at com.intellij.psi.impl.compiled.ClsFileImpl.wrapException(ClsFileImpl.java:388)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getMirror(ClsFileImpl.java:356)
	at com.intellij.psi.impl.compiled.ClsElementImpl.getMirror(ClsElementImpl.java:140)
	at com.intellij.psi.impl.compiled.ClsElementImpl.getTextOffset(ClsElementImpl.java:177)
	at com.intellij.ide.util.EditSourceUtil.getDescriptor(EditSourceUtil.java:41)
	at com.intellij.ide.util.PsiNavigationSupportImpl.getDescriptor(PsiNavigationSupportImpl.java:29)
	at com.intellij.psi.impl.PsiElementBase.navigate(PsiElementBase.java:194)
	at com.intellij.codeInsight.navigation.actions.UiKt.gotoTarget(ui.kt:29)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationOnlyHandler2.recordAndNavigate(GotoDeclarationOnlyHandler2.kt:95)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationOnlyHandler2.gotoDeclaration$intellij_platform_lang_impl(GotoDeclarationOnlyHandler2.kt:65)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationOrUsageHandler2.invoke(GotoDeclarationOrUsageHandler2.kt:64)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$actionPerformedImpl$0(CodeInsightAction.java:58)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$actionPerformedImpl$1(CodeInsightAction.java:64)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:153)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformedImpl(CodeInsightAction.java:55)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformed(CodeInsightAction.java:33)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.actionPerformed(GotoDeclarationAction.java:74)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:65)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$8(IdeKeyEventDispatcher.java:677)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:261)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:670)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:603)
	at com.intellij.openapi.keymap.impl.IdeMouseEventDispatcher.processEvent(IdeMouseEventDispatcher.java:271)
	at com.intellij.openapi.keymap.impl.IdeMouseEventDispatcher.dispatchMouseEvent(IdeMouseEventDispatcher.java:255)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:814)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:752)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: com.intellij.psi.impl.compiled.ClsElementImpl$InvalidMirrorException: stub:{}; mirror:null
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrorIfPresent(ClsElementImpl.java:256)
	at com.intellij.psi.impl.compiled.ClsMethodImpl.setMirror(ClsMethodImpl.java:212)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirror(ClsElementImpl.java:251)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrors(ClsElementImpl.java:272)
	at com.intellij.psi.impl.compiled.ClsClassImpl.setMirror(ClsClassImpl.java:451)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirror(ClsElementImpl.java:251)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrors(ClsElementImpl.java:272)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrors(ClsElementImpl.java:264)
	at com.intellij.psi.impl.compiled.ClsFileImpl.setFileMirror(ClsFileImpl.java:301)
	at com.intellij.psi.impl.compiled.ClsFileImpl.lambda$getMirror$1(ClsFileImpl.java:351)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:223)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getMirror(ClsFileImpl.java:350)
	... 37 more

**Comment by mprins** [comment]
getting similar error with Java Decompiler 0.8.1 and 
 
> IntelliJ IDEA 2021.2.1 (Ultimate Edition)
Build #IU-212.5080.55, built on August 24, 2021
Licensed to b3partners bv / Mark Prins
Subscription is active until February 17, 2022.
Runtime version: 11.0.11+9-b1504.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.11.0-27-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Non-Bundled Plugins: com.jetbrains.ChooseRuntime (1.2), com.intellij.ideolog (203.0.27.0), com.jetbrains.CyanTheme (1.2), com.jetbrains.plugins.ini4idea (212.4746.57), Error-prone plugin (212.4746.52), zielu.gittoolbox (212.7.6), jd-intellij (0.8.1), soapUI Plugin (3.5), com.oliverlockwood.plugins.jenkinsfile (1.0), mobi.hsz.idea.gitignore (4.2.0), ski.chrzanow.foldableprojectview (1.1.1), google-java-format (1.9.0.1), com.intellij.plugin.adernov.powershell (2.0.7), MavenRunHelper (4.15.212.000.0), org.jetbrains.plugins.rest (212.4746.57), net.seesharpsoft.intellij.plugins.csv (2.17.1), Pythonid (212.5080.64), org.jetbrains.kotlin (212-1.5.30-release-409-IJ4638.7), com.haulmont.jpab (4.5-212), izhangzhihao.rainbow.brackets (6.21), String Manipulation (8.15.203.000.3)
Kotlin: 212-1.5.30-release-409-IJ4638.7
Current Desktop: ubuntu:GNOME


```
jrt:///usr/lib/jvm/java-1.11.0-openjdk-amd64!/java.base/java/util/Map.class

com.intellij.diagnostic.PluginException: stub:[]; mirror:[PsiTypeParameter:K, PsiTypeParameter:V] [Plugin: jd-intellij]
	at com.intellij.psi.impl.compiled.ClsFileImpl.wrapException(ClsFileImpl.java:388)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getMirror(ClsFileImpl.java:356)
	at com.intellij.psi.impl.compiled.ClsElementImpl.getMirror(ClsElementImpl.java:140)
	at com.intellij.debugger.impl.DebuggerUtilsImpl.getPsiClassAndType(DebuggerUtilsImpl.java:156)
	at com.intellij.debugger.ui.tree.render.CachedEvaluator.initEvaluatorAndChildrenExpression(CachedEvaluator.java:50)
	at com.intellij.debugger.ui.tree.render.CachedEvaluator.lambda$getEvaluator$1(CachedEvaluator.java:89)
	at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$commitAndRunReadAction$9(PsiDocumentManagerBase.java:520)
	at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$commitAndRunReadAction$10(PsiDocumentManagerBase.java:545)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:854)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:543)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:520)
	at com.intellij.debugger.ui.tree.render.CachedEvaluator.getEvaluator(CachedEvaluator.java:89)
	at com.intellij.debugger.ui.tree.render.ExpressionChildrenRenderer.isExpandableAsync(ExpressionChildrenRenderer.java:162)
	at com.intellij.debugger.ui.tree.render.CompoundReferenceRenderer.isExpandableAsync(CompoundReferenceRenderer.java:84)
	at com.intellij.debugger.ui.impl.watch.ValueDescriptorImpl.lambda$calcRepresentation$3(ValueDescriptorImpl.java:355)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at com.intellij.debugger.ui.impl.watch.ValueDescriptorImpl.calcRepresentation(ValueDescriptorImpl.java:355)
	at com.intellij.debugger.ui.impl.watch.ValueDescriptorImpl.lambda$calcRepresentation$1(ValueDescriptorImpl.java:317)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at com.intellij.debugger.impl.DebuggerUtilsAsync.completeFuture(DebuggerUtilsAsync.java:496)
	at com.intellij.debugger.impl.DebuggerUtilsAsync$1.contextAction(DebuggerUtilsAsync.java:437)
	at com.intellij.debugger.engine.events.SuspendContextCommandImpl.action(SuspendContextCommandImpl.java:59)
	at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:43)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:154)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:29)
	at com.intellij.debugger.impl.InvokeThread.lambda$run$0(InvokeThread.java:138)
	at com.intellij.openapi.project.DumbService.runWithAlternativeResolveEnabled(DumbService.java:376)
	at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:125)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.lambda$run$0(InvokeThread.java:49)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:48)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.intellij.psi.impl.compiled.ClsElementImpl$InvalidMirrorException: stub:[]; mirror:[PsiTypeParameter:K, PsiTypeParameter:V]
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrors(ClsElementImpl.java:269)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrors(ClsElementImpl.java:264)
	at com.intellij.psi.impl.compiled.ClsTypeParametersListImpl.setMirror(ClsTypeParametersListImpl.java:34)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirror(ClsElementImpl.java:251)
	at com.intellij.psi.impl.compiled.ClsMethodImpl.setMirror(ClsMethodImpl.java:214)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirror(ClsElementImpl.java:251)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrors(ClsElementImpl.java:272)
	at com.intellij.psi.impl.compiled.ClsClassImpl.setMirror(ClsClassImpl.java:451)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirror(ClsElementImpl.java:251)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrors(ClsElementImpl.java:272)
	at com.intellij.psi.impl.compiled.ClsClassImpl.setMirror(ClsClassImpl.java:452)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirror(ClsElementImpl.java:251)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrors(ClsElementImpl.java:272)
	at com.intellij.psi.impl.compiled.ClsElementImpl.setMirrors(ClsElementImpl.java:264)
	at com.intellij.psi.impl.compiled.ClsFileImpl.setFileMirror(ClsFileImpl.java:301)
	at com.intellij.psi.impl.compiled.ClsFileImpl.lambda$getMirror$1(ClsFileImpl.java:351)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:223)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getMirror(ClsFileImpl.java:350)
	... 43 more
```

**Comment by dhalonen** [comment]
Also getting this.

**Comment by abn-dev-01** [comment]
IntelliJ IDEA 2021.2.2 (Ultimate Edition)
Build #IU-212.5284.40, built on September 14, 2021

Runtime version: 11.0.12+7-b1504.28 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4012M

same issue!

**Comment by Bujiangjiu3** [comment]
Also getting this.
